In [1]:
import os
import sys
from pathlib import Path

# 切换到项目根目录
project_root = str(Path.cwd().parent)
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# 开启自动重载，这样你修改 src 里的代码，Notebook 会自动同步
%load_ext autoreload
%autoreload 2

# 完美导入你的工具箱！
from src import config
from src import data_loader
from src import features

print("✅ 准备就绪，可以开始 EDA！")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Jupyter Notebook 环境
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Jupyter Notebook 环境
✅ 准备就绪，可以开始 EDA！

In [2]:
regular_results, tourney_results, seeds = data_loader.get_main_datasets(True)
submission_df = data_loader.get_submission_datasets()

In [3]:
tourney_results['Season'].unique()

array([2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, 2017, 2018, 2019, 2021, 2022, 2023, 2024, 2025])

In [4]:
submission_df = features.get_submission_teams(submission_df)

In [5]:
regular_results, tourney_results, seeds = features.process_after_year(regular_results, tourney_results, seeds)

In [6]:
regular_data, tourney_data = features.prepare_dataset(regular_results), features.prepare_dataset(tourney_results)

In [7]:
tourney_data,seeds_T1, seeds_T2=features.merge_seeds_and_tourney(tourney_data, seeds)

In [8]:
tourney_data, regular_data_mean_T1, regular_data_mean_T2 = features.add_regular_season_means(tourney_data ,regular_data)
tourney_data ,tourney_data_mean_T1, tourney_data_mean_T2= features.get_tourney_mean(tourney_data)

In [9]:
tourney_data.head()

,Season,DayNum,T2_TeamID,T2_Score,T1_TeamID,T1_Score,NumOT,T2_FGM,T2_FGA,T2_FGM3,...,T2_tour_avg_FTA,T2_tour_avg_OR,T2_tour_avg_DR,T2_tour_avg_Ast,T2_tour_avg_TO,T2_tour_avg_Stl,T2_tour_avg_Blk,T2_tour_avg_PF,T2_tour_avg_Poss,T2_tour_avg_PointDiff
0,2003,134,1411,74.666667,1421,81.777778,1,25.777778,59.555556,10.666667,...,23.228299,14.616146,21.325694,12.341667,15.895833,6.481250,0.882639,17.964410,68.266428,-7.111111
1,2003,136,1436,51.000000,1112,80.000000,0,20.000000,64.000000,4.000000,...,11.783854,8.949479,13.103472,3.230556,14.229167,6.481250,-0.450694,24.964410,66.608095,-29.000000
2,2003,136,1272,71.000000,1113,84.000000,0,25.000000,69.000000,7.000000,...,17.783854,21.949479,18.103472,6.230556,16.229167,1.481250,4.549306,16.964410,70.458095,-13.000000
3,2003,136,1166,73.000000,1141,79.000000,0,27.000000,60.000000,7.000000,...,10.783854,14.949479,20.103472,18.230556,16.229167,-0.518750,8.549306,19.964410,71.133095,-6.000000
4,2003,136,1301,65.777778,1143,67.555556,1,22.222222,49.777778,8.000000,...,16.117188,4.838368,28.436806,12.341667,14.118056,3.814583,8.882639,22.408854,67.555317,-1.777778

In [10]:
regular_data_mean_T2.columns

Index(['Season', 'T2_TeamID', 'T2_avg_Score', 'T2_avg_FGM', 'T2_avg_FGA',
       'T2_avg_FGM3', 'T2_avg_FGA3', 'T2_avg_FTM', 'T2_avg_FTA', 'T2_avg_OR',
       'T2_avg_DR', 'T2_avg_Ast', 'T2_avg_TO', 'T2_avg_Stl', 'T2_avg_Blk',
       'T2_avg_PF', 'T2_avg_opponent_Score', 'T2_avg_opponent_FGM',
       'T2_avg_opponent_FGA', 'T2_avg_opponent_FGM3', 'T2_avg_opponent_FGA3',
       'T2_avg_opponent_FTM', 'T2_avg_opponent_FTA', 'T2_avg_opponent_OR',
       'T2_avg_opponent_DR', 'T2_avg_opponent_Ast', 'T2_avg_opponent_TO',
       'T2_avg_opponent_Stl', 'T2_avg_opponent_Blk', 'T2_avg_opponent_PF',
       'T2_avg_PointDiff', 'T2_avg_Poss', 'T2_avg_opponent_Poss'],
      dtype='object')

In [11]:
regular_data_mean_T1[regular_data_mean_T1['Season']==2026]

,Season,T1_TeamID,T1_avg_Score,T1_avg_FGM,T1_avg_FGA,T1_avg_FGM3,T1_avg_FGA3,T1_avg_FTM,T1_avg_FTA,T1_avg_OR,...,T1_avg_opponent_OR,T1_avg_opponent_DR,T1_avg_opponent_Ast,T1_avg_opponent_TO,T1_avg_opponent_Stl,T1_avg_opponent_Blk,T1_avg_opponent_PF,T1_avg_PointDiff,T1_avg_Poss,T1_avg_opponent_Poss
13583,2026,1101,67.703704,23.081481,54.403704,5.559259,17.862963,15.981481,22.674074,8.318519,...,6.459259,21.911111,12.411111,15.396296,8.477778,4.607407,18.485185,-5.922222,70.322037,69.838611
13584,2026,1102,61.531250,21.750000,51.156250,6.531250,21.375000,11.500000,17.937500,5.812500,...,8.656250,24.250000,15.250000,9.812500,7.968750,3.531250,17.781250,-18.343750,67.301563,68.428906
13585,2026,1103,86.875000,31.156250,62.593750,10.875000,28.250000,13.687500,18.187500,9.562500,...,9.375000,19.718750,13.218750,12.375000,6.281250,2.843750,16.093750,12.375000,72.201562,72.275781
13586,2026,1104,90.987500,29.906250,65.431250,12.593750,35.162500,18.581250,24.287500,10.118750,...,11.606250,24.400000,13.843750,9.237500,6.368750,3.650000,19.681250,8.237500,76.217812,76.624844
13587,2026,1105,71.051852,23.307407,53.859259,6.392593,18.259259,18.044444,24.444444,7.670370,...,8.318519,22.877778,14.277778,10.448148,5.981481,3.011111,19.166667,-2.540741,68.325926,68.075648
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14306,2026,3477,61.535714,22.107143,58.357143,6.071429,20.107143,11.250000,15.464286,7.571429,...,10.964286,26.500000,13.750000,14.535714,8.464286,3.464286,16.571429,-6.000000,72.666964,72.375000
14307,2026,3478,55.350694,19.114583,51.524306,6.263889,19.826389,10.857639,13.868056,7.920139,...,10.555556,21.611111,15.017361,11.409722,8.864583,3.482639,15.614583,-13.694444,66.771354,68.025260
14308,2026,3479,64.419355,21.759857,56.222222,9.136201,27.738351,11.763441,15.526882,7.082437,...,10.168459,24.297491,15.422939,16.304659,7.516129,3.784946,16.272401,-9.053763,70.443369,70.439337
14309,2026,3480,69.467433,23.528736,56.544061,8.015326,24.578544,14.394636,20.532567,8.988506,...,10.206897,22.735632,13.099617,14.785441,8.383142,3.187739,18.375479,0.689655,73.929215,73.874138
14310,2026,3481,55.238683,20.333333,54.222222,4.954733,17.004115,9.617284,13.226337,10.884774,...,8.893004,20.267490,14.168724,13.921811,8.090535,2.596708,13.246914,-6.810700,66.517078,66.697634

In [12]:
tourney_data_mean_T2.columns

Index(['Season', 'T2_TeamID', 'T2_tour_avg_Score', 'T2_tour_avg_FGM',
       'T2_tour_avg_FGA', 'T2_tour_avg_FGM3', 'T2_tour_avg_FGA3',
       'T2_tour_avg_FTM', 'T2_tour_avg_FTA', 'T2_tour_avg_OR',
       'T2_tour_avg_DR', 'T2_tour_avg_Ast', 'T2_tour_avg_TO',
       'T2_tour_avg_Stl', 'T2_tour_avg_Blk', 'T2_tour_avg_PF',
       'T2_tour_avg_Poss', 'T2_tour_avg_PointDiff'],
      dtype='object')

In [13]:
submission_df = data_loader.get_submission_datasets()

In [14]:
tourney_data,  elos, elos_T1, elos_T2 = features.get_elo_rating(tourney_data, regular_data, 2)

In [15]:
tourney_data['Season'].unique()

array([2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, 2017, 2018, 2019, 2021, 2022, 2023, 2024, 2025])

In [16]:
tourney_data,  elos2_T1, elos2_T2 = features.modify_elo_rating_from_tourney(tourney_data, elos, 2)

In [17]:
tourney_data ,glm_quality_T1, glm_quality_T2 = features.get_glm_quality_features(tourney_data, regular_data, seeds)

Calculating GLM Quality: 100%|██████████| 23/23 [01:03<00:00,  2.77s/season]

In [18]:
tourney_data['T1_quality']

0       -3.099741
1       27.707625
2       19.701429
3       10.679634
4       16.066839
          ...
4815    46.428085
4816    38.654731
4817    46.677256
4818    48.509611
4819    51.390084
Name: T1_quality, Length: 4820, dtype: float64

In [19]:
tourney_data['Season'].unique()

array([2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, 2017, 2018, 2019, 2021, 2022, 2023, 2024, 2025])

In [20]:
submission = features.process_submission(submission_df, regular_data_mean_T1, regular_data_mean_T2,tourney_data_mean_T1, tourney_data_mean_T2, seeds_T1, seeds_T2, glm_quality_T1, glm_quality_T2, elos_T1, elos_T2, elos2_T1, elos2_T2)

In [21]:
submission['Season'].unique()

array([2026])

In [22]:
submission.drop_duplicates(inplace=True)

In [23]:
len(submission)

132133

In [24]:
from src import models

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Jupyter Notebook 环境

In [25]:
model, spline_model = models.train_and_calibrate_models(tourney_data, config.XGB_features, config.param, config.num_rounds, config.spline_t)

Season 2006 - PointDiff MAE: 8.5176
Season 2007 - PointDiff MAE: 8.2851
Season 2008 - PointDiff MAE: 9.8629
Season 2009 - PointDiff MAE: 9.2444
Season 2010 - PointDiff MAE: 9.7813
Season 2011 - PointDiff MAE: 9.7392
Season 2012 - PointDiff MAE: 8.3371
Season 2013 - PointDiff MAE: 10.3755
Season 2014 - PointDiff MAE: 9.7677
Season 2015 - PointDiff MAE: 7.9536
Season 2016 - PointDiff MAE: 10.0530
Season 2017 - PointDiff MAE: 10.1469
Season 2018 - PointDiff MAE: 10.3635
Season 2019 - PointDiff MAE: 8.7872
Season 2021 - PointDiff MAE: 10.6014
Season 2022 - PointDiff MAE: 10.1509
Season 2023 - PointDiff MAE: 9.4632
Season 2024 - PointDiff MAE: 9.4687
Season 2025 - PointDiff MAE: 9.8736

 Brier Score: 0.16605

In [26]:
regular_data.loc[regular_data['Season']==2026]

,Season,DayNum,T2_TeamID,T2_Score,T1_TeamID,T1_Score,NumOT,T2_FGM,T2_FGA,T2_FGM3,...,T1_Blk,T1_PF,T1_Is_Home,T2_Is_Home,T1_Poss,T2_Poss,PointDiff,Win,Gender,Win_Is_Home
118882,2026,0,1241,71.0,1103,85.0,0,24.0,61.0,11.0,...,6.0,13.0,H,H,72.775,75.175,14.0,1,1,H
118883,2026,0,1315,62.0,1104,91.0,0,24.0,62.0,5.0,...,7.0,15.0,H,H,77.825,76.075,29.0,1,1,H
118884,2026,0,1196,87.0,1112,93.0,0,30.0,70.0,7.0,...,5.0,22.0,N,N,80.050,83.250,6.0,1,1,N
118885,2026,0,1380,77.0,1116,109.0,0,27.0,69.0,12.0,...,4.0,18.0,H,H,81.775,81.400,32.0,1,1,H
118886,2026,0,1325,85.0,1117,89.0,0,31.0,63.0,8.0,...,2.0,27.0,A,A,75.300,77.450,4.0,1,1,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423427,2026,131,3471,60.0,3218,48.0,0,25.0,69.0,3.0,...,6.0,15.0,N,N,66.800,71.800,-12.0,0,0,N
423428,2026,132,3158,68.0,3220,56.0,0,23.0,61.0,9.0,...,4.0,17.0,N,N,64.375,63.975,-12.0,0,0,N
423429,2026,132,3192,79.0,3254,57.0,0,31.0,60.0,10.0,...,4.0,15.0,H,H,67.650,66.225,-22.0,0,0,H
423430,2026,132,3221,77.0,3250,70.0,0,31.0,60.0,5.0,...,2.0,12.0,H,H,63.700,64.700,-7.0,0,0,H
423431,2026,132,3293,91.0,3191,70.0,0,35.0,68.0,13.0,...,4.0,17.0,N,N,68.125,71.650,-21.0,0,0,N

In [27]:
regular_data_mean_T1.head()

,Season,T1_TeamID,T1_avg_Score,T1_avg_FGM,T1_avg_FGA,T1_avg_FGM3,T1_avg_FGA3,T1_avg_FTM,T1_avg_FTA,T1_avg_OR,...,T1_avg_opponent_OR,T1_avg_opponent_DR,T1_avg_opponent_Ast,T1_avg_opponent_TO,T1_avg_opponent_Stl,T1_avg_opponent_Blk,T1_avg_opponent_PF,T1_avg_PointDiff,T1_avg_Poss,T1_avg_opponent_Poss
0,2003,1102,57.250000,19.142857,39.785714,7.821429,20.821429,11.142857,17.107143,4.178571,...,9.607143,20.142857,9.142857,12.964286,5.428571,1.571429,18.357143,0.250000,55.161607,54.929464
1,2003,1103,75.967901,26.268313,54.051029,5.296296,15.611523,18.134979,24.580247,9.497119,...,11.443621,21.232922,14.907819,14.753909,6.218930,2.750617,21.566255,0.708642,68.516770,68.326358
2,2003,1104,69.015873,23.940476,56.964286,6.329365,19.805556,14.805556,20.849206,13.523810,...,10.857143,22.551587,11.638889,13.789683,5.503968,3.170635,19.170635,4.261905,66.577976,66.350397
3,2003,1105,70.400855,23.938462,60.519658,7.447009,20.373504,15.076923,21.348718,13.252137,...,12.901709,25.925641,15.561538,18.485470,9.217949,4.138462,18.683761,-4.843590,75.680812,74.780833
4,2003,1106,63.281746,23.309524,55.019841,6.083333,17.567460,10.579365,16.384921,12.234127,...,11.273810,22.273810,11.722222,15.003968,8.773810,3.154762,16.079365,-0.162698,67.552679,67.268552

In [28]:
result_df = models.predict_submission_ensemble(submission, model, spline_model, config.XGB_features, config.spline_t, config.aggression)

In [29]:
result_df.head()

               ID      Pred
0  2026_1101_1102  0.956715
1  2026_1101_1103  0.841279
2  2026_1101_1104  0.726333
3  2026_1101_1105  0.990000
4  2026_1101_1106  0.940912

In [30]:
len(result_df)

132133

In [31]:
result_df.to_csv('results11.csv', index=False)

In [ ]:
regular_data.columns

In [ ]:
regular_data = features.prepare_dataset(regular_results)
tourney_data = features.prepare_dataset(tourney_results)
# 统计每列的缺失值绝对数量
missing_counts = tourney_data.isnull().sum()

# 仅打印那些确实存在缺失值的列，让界面更清爽
print(missing_counts[missing_counts > 0])

let's take an example match to double check if the same match is entered correctly in our dataset

In [ ]:
len(tourney_data)

In [ ]:
t1, t2 = regular_data.loc[2,"T1_TeamID"], regular_data.loc[10,"T1_TeamID"]
match1 = (regular_data["T1_TeamID"] == t1) & (regular_data["T2_TeamID"] == t2)
match2 = (regular_data["T1_TeamID"] == t2) & (regular_data["T2_TeamID"] == t1)
regular_data.loc[(match1 | match2)]

In [ ]:
tourney_data=features.merge_seeds_and_tourney(tourney_data, seeds)

In [ ]:
import matplotlib.pyplot as plt

# let's see if __seed__ is predictive for predicting the point difference
tmpmean = tourney_data.pivot_table(columns="Gender", index="T1_seed", values="PointDiff", aggfunc="mean").ffill()
tmpstd = tourney_data.pivot_table(columns="Gender", index="T1_seed", values="PointDiff", aggfunc="std").ffill()

In [ ]:
fig, axis = plt.subplots(ncols=2, figsize=(12, 4))
(line_1,) = axis[0].plot(tmpmean.index, tmpmean[0], "b-")
fill_1 = axis[0].fill_between(tmpmean.index, tmpmean[0] - tmpstd[0], tmpmean[0] + tmpstd[0], color="b", alpha=0.1)
(line_2,) = axis[1].plot(tmpmean.index, tmpmean[1], "r--")
fill_2 = axis[1].fill_between(tmpmean.index, tmpmean[1] - tmpstd[1], tmpmean[1] + tmpstd[1], color="r", alpha=0.1)
plt.margins(x=0)
plt.legend([(line_1, fill_1), (line_2, fill_2)], ["Women", "Men"])

In [ ]:
tmpmean = tourney_data.pivot_table(columns="Gender", index="Seed_diff", values="PointDiff", aggfunc="mean").ffill()
tmpstd = tourney_data.pivot_table(columns="Gender", index="Seed_diff", values="PointDiff", aggfunc="std").ffill()

In [ ]:
fig, axis = plt.subplots(ncols=2, figsize=(12, 4))
(line_1,) = axis[0].plot(tmpmean.index, tmpmean[0], "b-")
fill_1 = axis[0].fill_between(tmpmean.index, tmpmean[0] - tmpstd[0], tmpmean[0] + tmpstd[0], color="b", alpha=0.1)
(line_2,) = axis[1].plot(tmpmean.index, tmpmean[1], "r--")
fill_2 = axis[1].fill_between(tmpmean.index, tmpmean[1] - tmpstd[1], tmpmean[1] + tmpstd[1], color="r", alpha=0.1)
plt.margins(x=0)
plt.legend([(line_1, fill_1), (line_2, fill_2)], ["Women", "Men"])

In [ ]:
tourney_data.columns

获取所有列的相关热力图

In [ ]:
cols = ['PointDiff','T2_TeamID', 'T2_Score', 'T1_TeamID', 'T1_Score',
       'NumOT', 'T2_FGM', 'T2_FGA', 'T2_FGM3', 'T2_FGA3', 'T2_FTM', 'T2_FTA',
       'T2_OR', 'T2_DR', 'T2_Ast', 'T2_TO', 'T2_Stl', 'T2_Blk', 'T2_PF',
       'T1_FGM', 'T1_FGA', 'T1_FGM3', 'T1_FGA3', 'T1_FTM', 'T1_FTA', 'T1_OR',
       'T1_DR', 'T1_Ast', 'T1_TO', 'T1_Stl', 'T1_Blk', 'T1_PF', 'T1_Poss',
       'T2_Poss',  'Seed_diff']
corr_matrix = tourney_data[cols].corr()
import seaborn as sns
import matplotlib.pyplot as plt
n_features = len(corr_matrix.columns)
# 每个格子约 0.8 英寸，留出边距
plt.figure(figsize=(max(12, n_features * 0.8), max(10, n_features * 0.8)))
sns.heatmap(corr_matrix, 
            annot=True, 
            fmt='.2f', 
            cmap='coolwarm', 
            center=0,
            annot_kws={"size": max(6, 10 - n_features//20)},  # 特征越多字体略小
            square=True,          # 强制格子为正方形
            cbar_kws={"shrink": 0.8, "pad": 0.02})
plt.title('Massey inter-system correlation heat map', fontsize=14, pad=20)
plt.xticks(rotation=45, ha='right', fontsize=9)
plt.yticks(fontsize=9)
plt.tight_layout()
plt.savefig('massey_corr_heatmap1.png', dpi=300, bbox_inches='tight')
plt.show()

In [ ]:
tourney_data = features.get_regular_mean(tourney_data ,regular_data)

In [ ]:
tourney_data.columns

In [ ]:
# using ELO rating system

def update_elo(winner_elo, loser_elo):
    expected_win = expected_result(winner_elo, loser_elo)
    change_in_elo = k_factor * (1 - expected_win)
    winner_elo += change_in_elo
    loser_elo -= change_in_elo
    return winner_elo, loser_elo


def expected_result(elo_a, elo_b):
    return 1.0 / (1 + 10 ** ((elo_b - elo_a) / elo_width))

base_elo = 1000
elo_width = 400
k_factor = 100

elos = []

for season in sorted(set(seeds['Season'])):
    current_data = regular_data.loc[regular_data['Season']==season]
    current_data = current_data.loc[current_data['Win']==1].reset_index(drop=True)
    all_teams = set(current_data['T1_TeamID']) | set(current_data['T2_TeamID'])
    elo = dict(zip(all_teams, [base＿elo] * len(all_teams)))
    for i in range(len(current_data)):
        w_team, l_team = current_data.loc[i, "T1_TeamID"], current_data.loc[i, "T2_TeamID"]
        w_elo, l_elo = elo[w_team], elo[l_team]
        w_elo_new, l_elo_new = update_elo(w_elo, l_elo)
        elo[w_team] = w_elo_new
        elo[l_team] = l_elo_new
    elo = pd.DataFrame.from_dict(elo, orient="index").reset_index()
    elo = elo.rename({"index": "TeamID", 0: "elo"}, axis=1)
    elo["Season"] = season
    elos.append(elo)
elos = pd.concat(elos)
elos_T1 = elos.copy().rename({"TeamID": "T1_TeamID", "elo": "T1_elo"}, axis=1)
elos_T2 = elos.copy().rename({"TeamID": "T2_TeamID", "elo": "T2_elo"}, axis=1)
tourney_data = pd.merge(tourney_data, elos_T1, on=["Season", "T1_TeamID"], how="left")
tourney_data = pd.merge(tourney_data, elos_T2, on=["Season", "T2_TeamID"], how="left")
tourney_data["elo_diff"] = tourney_data["T1_elo"] - tourney_data["T2_elo"]

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns  # 业界习惯简写为 sns
tmp = pd.merge(elos, tourney_data[['Season', 'T1_TeamID']].drop_duplicates(), 
               left_on = ['Season', 'TeamID'], 
               right_on = ['Season', 'T1_TeamID'],
               how = 'left')
plt.figure(figsize=(6,4))

# 未进入锦标赛的球队 Elo 分布
sns.histplot(tmp.loc[pd.isnull(tmp['T1_TeamID']),'elo'], 
             kde=False, color='blue', label='Not in Tourney', alpha=0.5)

# 进入锦标赛的球队 Elo 分布
sns.histplot(tmp.loc[~pd.isnull(tmp['T1_TeamID']),'elo'], 
             kde=False, color='orange', label='In Tourney', alpha=0.5)

plt.legend() # 显示图例，这样你才知道哪个颜色代表哪组球队
plt.show()

In [ ]:
tourney_data = features.get_glm_quality_features(tourney_data, regular_data, seeds)
tourney_data.head()

In [ ]:
# 统计每列的缺失值绝对数量
missing_counts = tourney_data.isnull().sum()

# 仅打印那些确实存在缺失值的列，让界面更清爽
print(missing_counts[missing_counts > 0])

In [ ]:
tourney_data.columns

In [ ]:
tourney_data['Win_Is_Home'].unique()

In [ ]:
tourney_data.columns

In [ ]:
tourney_data.head()

In [ ]:
submission.head()

In [ ]:
seeds.head()

In [ ]:
tourney_data.head()

In [ ]:
elos.head()

In [ ]:
tourney_data=features.modify_elo_rating_from_tourney(tourney_data, elos)

In [ ]:
tourney_data.head()

In [ ]:
tourney_data.columns

In [ ]:
tourney_data['T1_elo_tour']

In [ ]:
tourney_data['T1_elo']

In [ ]:
tourney_data_1, tourney_data_2 = features._get_mean_regular_data(tourney_data)

In [ ]:
tourney_data_1.head()

In [ ]:
regular_data['Season'].unique()

In [ ]:
seeds['Season'].unique()

In [ ]:
tourney_results['Season'].unique()

In [ ]:
regular_data.columns

In [ ]:
tourney_results.columns

In [ ]:
tourney_data.columns

In [ ]:
tourney_data = features.get_tourney_mean(tourney_data)

In [ ]:
tourney_data.columns.to_list()

In [ ]:
['1']+[c for c in tourney_data.columns.to_list() if '1' in c]